src/Entity/Invoice.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InvoiceRepository")
 */
class Invoice
{
    const WRONG_FILE_CHAR = ['.', '/', ' ', '\\', ',', ':', ';', "'", '"', '<', '>', '=', '@', '`', '{', '}', '*', '|'];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="userInvoices", cascade={"persist"})
     */
    private $byCompany;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $payTo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $invoiceNumber;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="invoices")
     */
    private $forCompany;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Product", inversedBy="invoices", cascade={"persist"})
     */
    private $products;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $salesDate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="invoices")
     */
    private $user;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->salesDate = new DateTime();
        $this->createdAt = new DateTime();
        $payTo = new DateTime();
        $payTo->modify('+14 days');
        $this->payTo = $payTo;
    }

    public function getTotal()
    {
        $total = 0;
        foreach ($this->products as $product) {
            $total += $product->getGrossValue() * $product->getQuantity();
        }

        return $total;
    }

    public function getNetTotal()
    {
        $total = 0;
        foreach ($this->products as $product) {
            $total += $product->getNetValue() * $product->getQuantity();
        }

        return $total;
    }

    public function getInvoiceNumberSlug()
    {
        return str_replace(self::WRONG_FILE_CHAR, '-', $this->getInvoiceNumber());
    }

    public function getCurrency()
    {
        return $this->products[0]->getCurrency();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getByCompany(): ?Company
    {
        return $this->byCompany;
    }

    public function setByCompany(?Company $byCompany): self
    {
        $this->byCompany = $byCompany;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPayTo(): ?\DateTimeInterface
    {
        return $this->payTo;
    }

    public function setPayTo(\DateTimeInterface $payFrom): self
    {
        $this->payTo = $payFrom;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getForCompany(): ?Company
    {
        return $this->forCompany;
    }

    public function setForCompany(?Company $forCompany): self
    {
        $this->forCompany = $forCompany;

        return $this;
    }

    public function overdue()
    {
        if ($this->payTo < new \DateTime()) {
            return true;
        }

        return false;
    }

    /**
     * @return string
     */
    public function getInvoiceNumber()
    {
        return $this->invoiceNumber;
    }

    /**
     * @param string $invoiceNumber
     */
    public function setInvoiceNumber($invoiceNumber): void
    {
        $this->invoiceNumber = $invoiceNumber;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
        }

        return $this;
    }

    public function getSalesDate(): ?\DateTimeInterface
    {
        return $this->salesDate;
    }

    public function setSalesDate(?\DateTimeInterface $salesDate): self
    {
        $this->salesDate = $salesDate;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function __clone()
    {
        if ($this->id) {
            $this->id = null;
            $this->setCreatedAt(new DateTime());
            $this->setSalesDate(new DateTime());
            $payTo = new DateTime();
            $payTo->modify('+14 days');
            $this->payTo = $payTo;
        }
    }
}

src/Form/InvoiceType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Invoice;
use App\Entity\Product;
use App\Repository\CompanyRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;
use Symfony\Contracts\Translation\TranslatorInterface;

class InvoiceType extends AbstractType
{
    private $security;
    private $translator;
    private $em;
    private $productRepository;

    public function __construct(Security $security, TranslatorInterface $translator, EntityManagerInterface $em, ProductRepository $productRepository)
    {
        $this->security = $security;
        $this->translator = $translator;
        $this->em = $em;
        $this->productRepository = $productRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('forCompany', EntityType::class, [
                'class' => Company::class,
                'required' => true,
                'label' => $this->translator->trans('invoice.company', [], 'labels'),
                'query_builder' => function (CompanyRepository $cr) {
                    return $cr->getQueryBuilderByUser($this->security->getUser());
                },
            ])
            ->add('salesDate', DateType::class, [
                'widget' => 'single_text',
                'label' => $this->translator->trans('invoice.salesDate', [], 'labels'),
            ])
            ->add('payTo', DateType::class, [
                'widget' => 'single_text',
                'label' => $this->translator->trans('invoice.payTo', [], 'labels'),
            ])
            ->add('comment', null, [
                'label' => $this->translator->trans('invoice.comment', [], 'labels'),
            ])
            ->add('products', CollectionType::class, [
                'label' => $this->translator->trans('invoice.products', [], 'labels'),
                'entry_type' => ProductType::class,
                'entry_options' => [
                    'required' => true,
                    'attr' => ['class' => 'row'],
                ],
                'allow_add' => true,
                'by_reference' => false,
            ])
            ->add('existProduct', EntityType::class, [
                'mapped' => false,
                'required' => false,
                'placeholder' => $this->translator->trans('invoice.products.choose', [], 'labels'),
                'class' => Product::class,
                'query_builder' => function (ProductRepository $pr) {
                    return $pr->queryProductByUser($this->security->getUser());
                },
                'label' => false,
                // 'choice_label' => 'name',
                'required' => false,
            ])
            ->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
                if (array_key_exists('products', $event->getData())) {
                    $products = $event->getData()['products'];
                    foreach ($products as $product) {
                        if (is_numeric($product['id']) && $oldProduct = $this->productRepository->findOneBy(['id' => $product['id']])) {
                            $oldProduct->setUser(null);
                        }
                    }
                } else {
                    $event->getForm()->get('products')->addError(
                        new FormError($this->translator->trans('invoice.error', [], 'labels'))
                    );
                }
            })
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Invoice::class,
        ]);
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Form\InvoiceType;
use App\Repository\CompanyRepository;
use App\Repository\InvoiceRepository;
use App\Services\InvoiceFactory;
use App\Services\Pagination;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class InvoiceController extends AbstractController
{
    /**
     * @var TranslatorInterface
     */
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    /**
     * @Route("/invoice", name="app_invoice")
     */
    public function index()
    {
        return $this->render('invoice/index.html.twig');
    }

    /**
     * @Route("/invoice/template/{id}", name="app_template")
     */
    public function template(Invoice $invoice)
    {
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
        $pdfOptions->set('isHtml5ParserEnabled', true);
        $pdfOptions->set('isRemoteEnabled', true);
        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('invoice/template.html.twig', [
            'invoice' => $invoice,
        ]);
        $html = mb_convert_encoding($html, 'ASCII');
        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        $dompdf->stream($invoice->getInvoiceNumberSlug().'.pdf', [
            'Attachment' => true,
        ]);

        return $this->render('invoice/template.html.twig', [
            'invoice' => $invoice,
        ]);
    }

    /**
     * @Route("/invoice/create/{id}", name="app_invoice_add")
     */
    public function createInvoice(Request $request, InvoiceFactory $invoiceFactory, EntityManagerInterface $em, CompanyRepository $companyRepository, Invoice $invoice = null, $id = null)
    {
        if (empty($this->getUser()->getCompanies()->getValues())) {
            $this->addFlash('noCompany', $this->translator->trans('noCompany', [], 'invoice'));

            return $this->redirectToRoute('app_company_add');
        }
        if (null == $invoice) {
            $newInvoice = $invoiceFactory->createInvoice($this->getUser());
        } else {
            if ($invoice->getUser() !== $this->getUser()) {
                throw $this->createAccessDeniedException();
            }
            $newInvoice = clone $invoice;
        }
        $form = $this->createForm(InvoiceType::class, $newInvoice);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $invoiceFactory->onInvoiceSubmitted($newInvoice, $this->getuser());
            $em->persist($newInvoice);
            $em->flush();

            return $this->redirectToRoute('app_invoice_list', [
                'id' => $newInvoice->getId(),
            ]);
        }

        return  $this->render('invoice/create.html.twig', [
            'form' => $form->createView(),
            'noProducts' => empty($this->getUser()->getProducts()->getValues()),
        ]);
    }

    /**
     * @Route("/invoice/list/{id}", name="app_invoice_list")
     */
    public function list(InvoiceRepository $invoiceRepository, Request $request, PaginatorInterface $paginator, Pagination $pagination, Invoice $invoice = null, $id = null)
    {
        $paginator = $pagination->getPagination($invoiceRepository, $request, $paginator, $this->getUser());

        return $this->render('invoice/list.html.twig', [
           'invoices' => $paginator,
           'invoice' => $invoice,
        ]);
    }

    /**
     * @Route("/invoice/{id}/remove", name="app_invoice_item_remove")
     */
    public function remove(Invoice $invoice, EntityManagerInterface $em)
    {
        $em->remove($invoice);
        $em->flush();

        return $this->redirectToRoute('app_invoice_list');
    }
}

templates/invoice/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.user.name|upper }}{% endblock %}

{% block body %}
    {{ form_start(form) }}

        {{ form_errors(form) }}
        {{ form_row(form.forCompany) }}
        {{ form_row(form.salesDate) }}
        {{ form_row(form.payTo) }}
        {{ form_row(form.comment) }}

        {{ form_label(form.products) }}
        {% if form.products|length < 1 %}
            {% do form.products.setRendered() %}
        {% endif %}
        <ul class="products list-group list-group-flush" data-prototype="{{ form_widget(form.products.vars.prototype)|e('html_attr') }}">
            {% if noProducts %}
                {% do form.existProduct.setRendered() %}
            {% else %}
                <li
                    class="list-group-item bg-transparent"
                    data-api-product="{{ path('api_product') }}"
                    data-api-product-remove="{{ path('api_product_remove') }}"
                >{{ form_row(form.existProduct) }}
                </li>
            {% endif %}
                <li class="list-group-item bg-transparent text-center" id="loadInvoiceProduct">
                    <div class="spinner-border text-info" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </li>
            {% for product in form.products %}
                <li class="list-group-item bg-transparent new-product-form">
                    <a href="#" class="remove-product">x</a>
                    {{ form_errors(product) }}
                    {{ form_widget(product) }}
                </li>
                <br>
            {% endfor %}
        </ul>
        <div class="text-right sticky-position">
                        <button type="submit" class="btn btn-primary ">{{ 'button.create'|trans([], 'main')|upper }}</button>
        </div>

    {{ form_end(form) }}
    <a href="#" id="add_new_product" class="btn btn-info btn-sm">{{ 'invoice.add'|trans([], 'labels')|upper }}</a>
{% endblock %}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.user.name|upper }}{% endblock %}

{% block body %}
    <div class="text-center">
        <h1> <b>{{ app.user.name|upper }}</b></h1>
    </div>
    <p class="lead">{{ 'title'|trans([], 'invoice') }}</p>
    <hr class="my-5">

    <div class="row justify-content-around">
        <div class="col-3 button_cont">
            <a class="button" href="{{ path('app_invoice_list') }}" role="button">
                <i class="fas fa-file-invoice-dollar fa-2x mb-2"></i>
                <p>{{ 'invoice.list'|trans([], 'labels')|upper }}</p>
            </a>
        </div>
        <div class="col-3 button_cont">
            <a class="button" href="{{ path('app_invoice_add') }}" role="button">
                <i class="fas fa-plus fa-2x mb-2"></i>
                <p>{{ 'invoice.create'|trans([], 'labels')|upper }}</p>
            </a>
        </div>

        <div class="col-3 button_cont">
            <a class="button" href="{{ path('app_company_list') }}" role="button">
                <i class="far fa-address-book fa-2x mb-2"></i>
                <p>{{ 'invoice.companies'|trans([], 'labels')|upper }}</p>
            </a>
        </div>

        <div class="col-3 button_cont">
            <a class="button" href="{{ path('app_settings') }}" role="button">
                <i class="fas fa-cog fa-2x mb-2"></i>
                <p>{{ 'invoice.settings'|trans([], 'labels')|upper }}</p>
            </a>
        </div>
    </div>

{% endblock %}

templates/invoice/list.html.twig
{% extends 'defaultList.html.twig' %}

{% block header_right %}
    <a class="btn btn-primary mb-2" href="{{ path('app_invoice_add') }}">{{ 'button.add'|trans([], 'main') }}</a>
{% endblock %}

{% block table_head %} 
    <th scope="col">{{ 'invoice.createdAt'|trans([], 'labels') }}</th>
    <th scope="col">{{ 'invoice.number'|trans([], 'labels') }}</th>
    <th scope="col">{{ 'invoice.forCompany'|trans([], 'labels') }}</th>
    <th scope="col">{{ 'invoice.value'|trans([], 'labels') }}</th>
    <th scope="col">{{ 'invoice.overdue'|trans([], 'labels') }}</th>
{% endblock %}

{% block table_body %}
    {% for invoice in invoices %}
        <tr>
            <td> {{ invoice.createdAt|date('Y/m/d') }} </td>
            <td> {{ invoice.invoiceNumber }} </td>
            <td> {{ invoice.forCompany }} </td>
            <td> {{ invoice.getTotal }} {{ invoice.getCurrency }}</td>
            <td>
                {% if invoice.overdue %}
                    <div class="alert-danger text-center"> <i class="fas fa-thumbs-down text-center"></i></div>
                {% else %}
                    <div class="alert-success text-center"> <i class="fas fa-thumbs-up"></i></div>
                {% endif %}
            </td>
            <td>
                <div class="row justify-content-start">
                    <a href="{{ path('app_invoice_item_remove' , {'id':invoice.id}) }}" class="col-3 delete-button"><i class="far fa-trash-alt "></i></a>
                    <a href="{{ path('app_template' , {'id':invoice.id}) }}" class="col-3 delete-button"><i class="fas fa-file-download"></i></a>
                    <a href="{{ path('app_invoice_add' , {'id':invoice.id}) }}" class="col-3 delete-button"><i class="fas fa-redo-alt"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

{% block navigation %}
    {{ knp_pagination_render(invoices) }}
    {% if invoice is not null %}
        <div id="myModal" class="modal fade" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">{{ invoice.invoiceNumber }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>{{ 'invoice.info'|trans([], 'labels') }}</p>
                        <a role="button" href="{{ path('app_template', {'id' : invoice.id }) }}" class="btn btn-primary">{{ 'button.download'|trans([], 'labels') }}</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/invoice/template.html.twig
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ invoice.invoiceNumber }}</title>
    <style>
        @page { margin: 0; }
        body {
            padding: 100px;
            margin: 0;
            font-size: .7em;
        }
        table {
            width: 100%;
        }
        .table-main, .table-logo, .table-footer{
            text-align: center;
        }
        .table-logo {
            width: 60%;
        }
        .table-main td, .table-main th {
            padding: 10px;
        }
        ul {
            list-style: none;
        }
        .product-name-table {
            width: 50%;
        }

        .table-main tr:nth-child(even) {
            background-color: #dddddd;
        }
        .align-left{
            text-align: left;
        }


    </style>
<body>
    <h1>{{ 'invoice.number'|trans([], 'labels') }}: {{ invoice.invoiceNumber }}</h1>
    <table class="table-header">
        <tr>
            <td>
                <table>
                    <tr>
                        <td>{{ 'invoice.createdAt'|trans([], 'labels') }}:</td>
                        <td>{{ invoice.createdAt|date("m/d/Y") }}<td/>
                    </tr>
                    <tr>
                        <td>{{ 'invoice.salesDate'|trans([], 'labels') }}:</td>
                        <td>{{ invoice.salesDate|date("m/d/Y") }}<td/>
                    </tr>
                    <tr>
                        <td>Termin zaplaty:</td>
                        <td>{{ invoice.payTo|date("m/d/Y") }}<td/>
                    </tr>
                </table>
            </td>
            <td class="table-logo">
                <h1>{{ invoice.byCompany.name }}</h1>
            </td>
        </tr>
    </table>

    <hr>
    <br>
    <table>
        <tr>
            <th class="align-left">{{ 'template.seller'|trans([], 'labels')|capitalize }}:</th>
            <th class="align-left">{{ 'template.buyer'|trans([], 'labels')|capitalize }}:</th>
        </tr>
        <tr>
            <td> {{ invoice.byCompany }} </td>
            <td> {{ invoice.forCompany }} </td>
        </tr>
        <tr>
            <td>
                {{ invoice.byCompany.street }}
                {{ invoice.byCompany.stNumber }}
                {{ invoice.byCompany.postCode }}
                {{ invoice.byCompany.city }}
            <td>
                {{ invoice.forCompany.street }}
                {{ invoice.forCompany.stNumber }}
                {{ invoice.forCompany.postCode }}
                {{ invoice.forCompany.city }}
            </td>
        </tr>
        <tr>
            <td>
                {% if invoice.byCompany.nip is not empty%}
                    NIP: {{ invoice.byCompany.nip }}
                {% endif %}
            </td>
            <td>
                {% if invoice.forCompany.nip is not empty%}
                    NIP: {{ invoice.forCompany.nip }}
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>
                {% if invoice.byCompany.contactEmail is not empty%}
                    Email: {{ invoice.byCompany.contactEmail }}
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>
                {% if invoice.byCompany.accountNumber is not empty%}
                    {{ 'template.accountNumber'|trans([], 'labels') }}: 
                    {{ invoice.byCompany.accountNumber }}
                {% endif %}
            </td>
        </tr>
    </table>

    <br>

    <table class="table-main">
        <tr>
            <th class="product-name-table">{{ 'template.productService'|trans([], 'labels')|upper }}</th>
            <th>{{ 'template.quantity'|trans([], 'labels')|upper }}</th>
            <th>{{ 'template.netPrice'|trans([], 'labels')|upper }}</th>
            <th>{{ 'template.netValue'|trans([], 'labels')|upper }}</th>
            <th>{{ 'template.vat'|trans([], 'labels')|upper }}</th>
            <th>{{ 'template.grossValue'|trans([], 'labels')|upper }}</th>
        </tr>
        {% for product in invoice.products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.quantity }}</td>
                <td>{{ product.netValue }} {{ product.currency }}</td>
                <td>{{ (product.netValue * product.quantity)|number_format(2) }} {{ product.currency }}</td>
                <td>{{ product.vat }} %</td>
                <td>{{ (product.grossValue * product.quantity)|number_format(2)  }} {{ product.currency }}</td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <hr>

    <table class="table-footer">
        <tr>
            <td class="product-name-table"></td>
            <td>{{ 'template.netTotal'|trans([], 'labels')|capitalize }}:</td>
            <td><b>{{ invoice.netTotal|number_format(2) }} {{ invoice.products[0].currency }}</b></td>
            <td>{{ 'template.grossTotal'|trans([], 'labels')|capitalize }}:</td>
            <td><b>{{ invoice.getTotal|number_format(2) }} {{ invoice.products[0].currency }}</b></td>
        </tr>
    </table>
    <p>{{ invoice.comment }}</p>
</body>
</html>